### ISSUE TITLE
blaze incompatible 

### ISSUE THREAD

**Issue by scottmcpherson** [lgollut/meteor-foundation5-sass#2]
I've been struggling trying to get this package to work with meteor blaze-rc0. What do we have to do to get this working?

![screen shot 2014-03-07 at 7 24 01 pm](https://f.cloud.github.com/assets/2382172/2363863/0b19c848-a658-11e3-8e65-6d3e6d9ab321.png)

**Comment by lgollut** [comment]
Hi,
Thanks for reporting that ! It seems that blaze's jQuery dependency is a bit tighter than with spark. That means the way Meteorite unofficial [jQuery package](http://beta.atmospherejs.com/package/jquery) used here to replace v1.x with v2.x no longer work...

The [Dom Backend connector](https://github.com/meteor/meteor/wiki/Using-Blaze#wiki-events-use-jquery) seems to achieve that but I can't figure out how for now...

**Comment by lgollut** [comment]
I juste release a new branch "ui" to work with 0.8.0-rc1.
I've dropped the jQuery 2 atmosphere package to use the default implementation coming with Meteor.
Be aware of the name change for the Spacebars helper...

**Comment by rshah** [comment]
First i have this working in meteor 0.7.2.
But i cannot make it work in meteor 0.8.0-rc6 or later.
I already switched to your 'ui' branch but  the errors mentioned above still exist.

**Comment by rshah** [comment]
Finally i managed to make the 'ui' branch working.
@scott-mcpherson, please try below after you installed normal foundation5-sass branch:
- remove old packages:
  rm -fr ~/.meteorite/packages/jquery/
  rm -fr ~/.meteorite/packages/scss
- mrt add jquery2 
- switch foundation5-sass into 'ui' branch
- mrt update

finally replace the old init code with  {{initFoundation}}
