### ISSUE TITLE
Consider to upgrade the foundation to version 5.2.x

### ISSUE THREAD

**Issue by rshah** [lgollut/meteor-foundation5-sass#5]
Please consider to upgrade the foundation to ver 5.2.x.
In current version  the menu in mobile browser, the icon for stacked menu symbol is not properly displayed (little cut on the right side).

I tried manually update the foundation to ver 5.2.x then the problem was gone.

**Comment by lgollut** [comment]
Hi,
Just release a new branch 5.2.x with foundation 5.2.1. Please, give it a try in your project and let me know if all is ok !

**Comment by rshah** [comment]
@lgollut, thanks for creating this branch.
The menu now displayed properly.

Great.

**Comment by lgollut** [comment]
Hi,
I merged 5.2.x into master and publish v0.0.13 on atmospherejs. You can mrt update your app with default settings in your root smart.json and all should be ok.

**Comment by payner35** [comment]
possible to bump to 5.2.2  There is a few bugs with orbit slider on Android. https://github.com/zurb/foundation/issues/4717
